language: ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

gemfile:
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.0.beta1

before_install:
  - gem update bundler

script:
  - bundle exec rspec
